### ISSUE TITLE
feature request: glob patterns

### ISSUE THREAD

**Issue by ronkorving** [pigcan/extra-watch-webpack-plugin#15]
Hi, this is really a great plugin, thanks for making it!

I have one feature request...
It would be so powerful if you could watch [glob](https://www.npmjs.com/package/glob) patterns.

```js
// webpack.config.js
import ExtraWatchWebpackPlugin from 'extra-watch-webpack-plugin';
......
{
  plugins: [
    new ExtraWatchWebpackPlugin({
      files: [ 'path/*/file/*.js' ]
    }),
  ],
}
```

A very short feature request, but not sure what else I can say about it :) Thoughts?

**Comment by pigcan** [comment]
Hi @ronkorving it's a good idea. PR is welcomed.

If you do not have the time I would like to work on it this weekend.

**Comment by ronkorving** [comment]
@pigcan As you may have noticed, I haven't had the time yet, and I don't expect that to change really soon. Feel free to pick it up :)

**Comment by pigcan** [comment]
Supported

**Comment by ronkorving** [comment]
Fantastic! Thanks 👍
